/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#2b160f",
        primary: "#e4beb2",
        "surface-tint": "#e4beb2",
        "on-tertiary-fixed": "#201a18",
        "on-secondary": "#3a2e2a",
        "on-primary-fixed-variant": "#5b4137",
        secondary: "#d6c3bc",
        "surface-bright": "#3c3837",
        "error-container": "#93000a",
        "tertiary-container": "#7c7370",
        surface: "#161312",
        "on-tertiary-container": "#fffcff",
        "on-background": "#e8e1df",
        "surface-container": "#221f1e",
        "tertiary-fixed": "#ece0dc",
        "on-primary": "#422b22",
        "secondary-fixed": "#f2ded8",
        "on-secondary-fixed": "#231915",
        "on-error": "#690005",
        "primary-fixed-dim": "#e4beb2",
        "secondary-container": "#534642",
        "inverse-on-surface": "#33302e",
        "on-surface-variant": "#d4c3be",
        "surface-container-high": "#2d2928",
        "on-primary-container": "#fffcff",
        "inverse-surface": "#e8e1df",
        "primary-container": "#8d6e63",
        "primary-fixed": "#ffdbce",
        "surface-container-lowest": "#100e0d",
        "on-tertiary-fixed-variant": "#4c4542",
        "surface-variant": "#383433",
        "surface-dim": "#161312",
        tertiary: "#cfc4c0",
        "on-surface": "#e8e1df",
        outline: "#9c8e89",
        "tertiary-fixed-dim": "#cfc4c0",
        "secondary-fixed-dim": "#d6c3bc",
        "on-tertiary": "#352f2d",
        "on-secondary-fixed-variant": "#51443f",
        "surface-container-low": "#1e1b1a",
        "on-error-container": "#ffdad6",
        background: "#161312",
        error: "#ffb4ab",
        "inverse-primary": "#75584d",
        "outline-variant": "#504441",
        "surface-container-highest": "#383433",
        "on-secondary-container": "#c7b5ae",
        "dark-brown": "#2b160f",
        "soft-gold": "#d4af37"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "20px",
        gutter: "24px",
        unit: "8px",
        "section-gap": "120px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        headline: ["Playfair Display", "serif"],
        display: ["Playfair Display", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        serif: ["Playfair Display", "serif"]
      },
      fontSize: {
        "body-lg": ["18px", {lineHeight: "28px", fontWeight: "400"}],
        "label-sm": ["12px", {lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600"}],
        "headline-lg": ["40px", {lineHeight: "48px", fontWeight: "500"}],
        "headline-lg-mobile": ["32px", {lineHeight: "40px", fontWeight: "500"}],
        "body-md": ["16px", {lineHeight: "24px", fontWeight: "400"}],
        "headline-md": ["28px", {lineHeight: "36px", fontWeight: "500"}],
        "display-lg": ["64px", {lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "600"}]
      }
    },
  },
  plugins: [],
}
